### ISSUE TITLE
Spotify?

### ISSUE THREAD

**Issue by thereaderfortyfive** [rryam/MusadoraKit#10]
Does this also have Spotify capability with Spotify iOS SDK? 

It would be cool to have two sided. A Side: Apple, B SIDE: Spotify iOS.

**Comment by nevercode-rudrank** [comment]
Hi there @thereaderfortyfive! 

I did try Spotify SDK but found it difficult to work with, so I abandoned the thought of adding it to MusadoraKit

**Comment by rudrankriyam** [comment]
Hi there @thereaderfortyfive!

I did try Spotify SDK but found it difficult to work with, so I abandoned the thought of adding it to MusadoraKit

**Comment by paulcanyon** [comment]
Maybe ask someone from SpotifyKit GitHub repo to help? @rudrankriyam

**Comment by paulcanyon** [comment]
Spotify SDK is difficult to work with, I have first hand experience... very hard fail.

**Comment by rudrankriyam** [comment]
Hi @paulcanyon, I have no plans to add Spotify support in the near future. Cheers!

**Comment by rudrankriyam** [comment]
Hi @paulcanyon and @thereaderfortyfive, just want to let you know I've plans to support SpotifySDK, but only the Web REST APIs. The wrapper will be created in such a way that you can reuse your MusicKit knowledge and use the convenient async/await syntax. But it will be in a different framework.

Unfortunately, No ETA.

**Comment by rudrankriyam** [comment]
I have finally decided I want to focus fully on Apple Music!
