### ISSUE TITLE
Cannot find library song with MPMediaItem playbackStoreID

### ISSUE THREAD

**Issue by aeip** [rryam/MusadoraKit#12]
I'm trying to convert a list of MPMediaItems to their cloud version but am I getting the following error from the below code:

**The specified music item could not be found for 1631024269.**

Code: 
```
@State var songs = [MPMediaItem]()

            let list = songs[0...19].map { MusicItemID(stringLiteral: $0.playbackStoreID) }
            let testSongs = try await MusadoraKit.librarySong(id: list[0])
            print(testSongs.title)
```

I feel like it should work because MusadoraKit.librarySong(id: ) takes a MusicItemID. And I have received that from an MPMediaItem's playbackStoreID.

Am I just searching with the wrong function from Musadora Kit?
Thank you

**Comment by rudrankriyam** [comment]
`1631024269` is a MusicItemID for a song in the Apple Music catalogue, not a user's library one. Library one is like `i.gelNOzPuL41Lxo`

**Comment by rudrankriyam** [comment]
Can you try the `MusadoraKit.catalogSong(id:)` instead? Does that work? Because `playbackStoreID` as far as I remember is the catalog ID

**Comment by aeip** [comment]
> Can you try the `MusadoraKit.catalogSong(id:)` instead? Does that work? Because `playbackStoreID` as far as I remember is the catalog ID

Yes that works perfectly!
