### ISSUE TITLE
LibraryPlaylistCreation - warnings. 

### ISSUE THREAD

**Issue by raymondwelch33** [rryam/MusadoraKit#17]
My issue is regarding the two '#TODO' warning notes in the code. 

#warning("TODO: ADD RELATIONSHIPS")
#warning("TODO: ADD OPTION TO ADD TRACKS.")

When can we expect relationship and add track to playlist functions in the playlist class? 

Thanks!

**Comment by rudrankriyam** [comment]
Hi @raymondwelch33! Thank you for using MusadoraKit! 

Unfortunately, for playlist one, MusicKit is limiting the development as you cannot get relationships using the Apple Music API. I am thinking of creating a custom structure for it. No ETA, but hopefully should be done soon.

**Comment by rudrankriyam** [comment]
Hi @raymondwelch33. 

I've added the option to create a playlist but only with songs at the moment. Let me know if it works for you.

Usage:

```swift
let song = try await MusadoraKit.catalogSong(id: "1651994123")
let playlist = try await MusadoraKit.createPlaylist(name: "TESTING SONGS", items: .init(arrayLiteral: song))
```

**Comment by rudrankriyam** [comment]
You can also add music videos to a playlist.

**Comment by rudrankriyam** [comment]
Made the package type automatic in Version 1.9.2

**Comment by rudrankriyam** [comment]
Added in Version 1.9.3. See the release notes for usage 

https://github.com/rryam/MusadoraKit/releases/tag/v1.9.3
