### ISSUE TITLE
Can you please provide an example for boilerplate for each function in your framework?

### ISSUE THREAD

**Issue by shyamalschandra** [rryam/MusadoraKit#21]
Can you please provide an example for boilerplate for each function in your framework?

**Comment by rudrankriyam** [comment]
You should find the documentation pretty exhaustive, but I'll add more. Here's the documentation that uses DocC: https://rryam.github.io/MusadoraKit/documentation/musadorakit/mcatalog/song(id:fetch:)-73pfi

![Screenshot 2023-01-26 at 4 10 28 PM](https://user-images.githubusercontent.com/30552772/214816139-c4aa3559-df41-4cda-b7a6-84ead3161ab9.png)

**Comment by shyamalschandra** [comment]
@rudrankriyam: Are there comments explaining for each line of code in the source code very clearly and plenty of parameter-sweeped examples for each overloaded function signature for the API for MusadoraKit?  I don't have time to reverse-engineer each line of code.

**Comment by jordibruin** [comment]
@shyamalschandra make your own framework if you think you can do better.

**Comment by shyamalschandra** [comment]
![Screen Shot 2023-01-27 at 1 54 19 AM](https://user-images.githubusercontent.com/9545735/215035938-19e5fe33-1b54-4240-bf4b-a6fea32094d0.png)

@rudrankriyam: First of all, there is **sparse** documentation on MusicKit from Apple.  Second, where did you learn software engineering?  Do you have the proper workflow (spec written by a project manager, UML documentation written by an architect, pseudo-algorithms written by a theoretician, design-patterned code written by a "real" software engineer, and industrial-track test cases (regression and unit along with A/B testing) by a test engineer?  The numbers don't lie according to this **cloc** program output.  There are **162** files of Swift where there are **4,790** lines of Swift code and only **2,826** lines of comments.  In my high opinion, that is definitely not extensive documentation, that is sparse or nothing documentation.  To be completely honest, if you want to showcase your talents to the world, I would highly recommend taking a software engineering class along with a technical writing class in high school or college.  Which schools did you go to and what Swift courses in software engineering methodologies did you take?  Please answer and be upfront.  What books did you read?  I worked in the industry and I know what I am **talking** about.  Case not closed.

**Comment by shyamalschandra** [comment]
@rudrankriyam & @jordibruin: There are **only** 12 sparsely documented Swift-written packages on Github.
[Link to MusicKit topic from Github](https://github.com/topics/musickit?l=swift)

Plus, there are only 165 answers to questions on StackOverflow.

[Link to MusicKit topic from StackOverflow](https://stackoverflow.com/questions/tagged/apple-musickit)

Facts don't lie.  Prove me wrong.  I don't have time to go through each package to find no documentation like the official non-documented API from Apple Corporation in Cupertino, CA.

**Comment by martinmitrevski** [comment]
@shyamalschandra I want to get started with your 1vs1-pong project: https://github.com/shyamalschandra/1vs1-pong.

Where can I find the extensive documentation to get me started? "I don't have time to reverse-engineer each line of code.".

Would be nice to walk the talk on this one, thanks!

**Comment by codymikol** [comment]
This thread is amazing, thanks for the laugh
