### ISSUE TITLE
Query regarding fetch of loved / disliked songs.

### ISSUE THREAD

**Issue by aspeckt-112** [rryam/MusadoraKit#26]
Hi.

I apologise if I'm out of line to ask this here, but I've just stumbled across your awesome library and I was curious.

Basically what I'm trying to do is create a playlist of everything I've ever "Loved" and "Disliked" in Apple Music - regardless of if those songs are in my library or not. I can't see a clean way to do this in MusicKit or via the Apple Music API. Frankly it seems insane Apple don't just surface that information to you like Spotify does - but I digress.

Looking at MusadoraKit, would it be possible to call MLibrary.recentlyPlayedSongs and increment the offset until "hasNextBatch" is false, and then pass the song ID(s) to another function to get the rating?

I will add, I'm just hacking for myself right now. It doesn't need to be fast or pretty :)

Again, I do apologise if this isn't the right place to ask, but it seemed like a good place to start.

**Comment by rudrankriyam** [comment]
Heya there! Thank you for asking your question! I love it.  

Your approach is the best one for me. Just thinking out loud:
1. Use `let songs = try await MLibrary.recentlyPlayedSongs()` to get the songs, let's say with limit of 25.
2. Pass it directly to the method `getRatings(for: songs)`. 
3. Do this till `hasNextBatch` is false.

Let me know how it goes!

**Comment by aspeckt-112** [comment]
Appreciate the reply!

I’ve stepped away from my computer for the evening, but I’ll have a go tomorrow and let you know.

I’m a .NET developer by trade, but I’m learning Swift in my free time, so it’s quite a lot to take in all at once! 😁

**Comment by rudrankriyam** [comment]
> I’m a .NET developer by trade, but I’m learning Swift in my free time, so it’s quite a lot to take in all at once! 😁

I'll help you with the code if that's ok with you!

**Comment by aspeckt-112** [comment]
Very kind of you to offer. I’ll try and figure it out first, but I’ll let you know if I get stuck.

Thanks 🙏

**Comment by rudrankriyam** [comment]
@aspeckt-112 how did it go?

**Comment by aspeckt-112** [comment]
@rudrankriyam I’ve not had time to look yet. I’m currently in the process of moving house. Very stressful. 😊

I’m planning to have a look tomorrow for an hour or so.

**Comment by aspeckt-112** [comment]
@rudrankriyam So I've had a play. Everything looks like it should work but upon running, I get the error:

> Ratings not allowed for resource type 'library-songs'

Here's the code for my entire view:

`import SwiftUI
import MusadoraKit
import MusicKit

struct LovedSongsScreen: View {
    var body: some View {
        listOfSongs
            .task {
                do {
                    var offset = 0
                    var hasMoreSongs = true
                
                    while hasMoreSongs {
                        let songs  = try await MLibrary.recentlyPlayedSongs(offset: offset)
                        let ratings = try await MLibrary.getRatings(for: songs)
                        hasMoreSongs = songs.hasNextBatch
                        offset += 1
                    }
                    
                } catch {
                    print("Search request failed with error: \(error).")
                }
            }
    }
    
    private var listOfSongs: some View {
        List {
            
        }
    }
}

struct LovedSongsScreen_Previews: PreviewProvider {
    static var previews: some View {
        LovedSongsScreen()
    }
}
`

Any idea what might be going wrong?

**Comment by rudrankriyam** [comment]
Oops. This does not look good. I'll have to verify it on my end, give me some time!

**Comment by aspeckt-112** [comment]
Take as long as you need. It’s open source, and you’re giving your code and time away for free. You owe me nothing. 👍
