### ISSUE TITLE
Make the linting plugin optional?

### ISSUE THREAD

**Issue by ericlewis** [rryam/MusadoraKit#29]
**Is your feature request related to a problem? Please describe.**
When using MusadoraKit the first time, it appears that Swift lint gets pulled in and ran as part of the builds steps.

**Describe the solution you'd like**
It shouldn't do this.

**Describe alternatives you've considered**
Removing it from the public package.

**Additional context**
N/A

**Comment by rudrankriyam** [comment]
PR please. 

Also, for DocC, I do not want the client to have the plugin, too, need to do something like how RevenueCat does it. https://github.com/RevenueCat/purchases-ios/blob/main/Package.swift

**Comment by rudrankriyam** [comment]
Removed.
