### ISSUE TITLE
Ask for user permissions on interaction with any async api

### ISSUE THREAD

**Issue by ericlewis** [rryam/MusadoraKit#31]
**Is your feature request related to a problem? Please describe.**
Asking for permission is a separate issue (which is also not documented here)

**Describe the solution you'd like**
Ideally, any request to an async / await API could block and then perform authorization tasks for the developer. 

**Describe alternatives you've considered**
None really, mostly just an idea.

**Additional context**
I think there is a few Apple APIs which take this approach now.

**Comment by rudrankriyam** [comment]
I need to think if this should be handled on the client side or the package side. For now, I will mark it as not planned. Thanks!!
