### ISSUE TITLE
Quickstart Documentation

### ISSUE THREAD

**Issue by ericlewis** [rryam/MusadoraKit#32]
**Is your feature request related to a problem? Please describe.**
There is a number of things a person must do to *actually* use Muse. 

**Describe the solution you'd like**
We should add documentation around things like the required usage permissions as well as the need for setting up Media API Tokens.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ericlewis** [comment]
interesting, it seems also that the media api thing is only depending on what API you use.

**Comment by ericlewis** [comment]
should probably consider adding the simplest example of playing a song.

**Comment by rudrankriyam** [comment]
> There is a number of things a person must do to actually use Muse.
There are a number of things a person must do to work with Apple Music in general. Create an identifier with MusicKit service, update the Info.plist with the music usage description, get authorisation via MusicKit `MusicAuthorization` structure. No API token to deal with now

After that MusadoraKit comes into play, but yeah need to document nonetheless. It is scattered around in some articles of mine, will copy-paste.

**Comment by rudrankriyam** [comment]
> should probably consider adding the simplest example of playing a song.

I added a few helper methods in `APlayer` and `SPlayer` that I have not documented yet. Go to-do

**Comment by rudrankriyam** [comment]
Update with #34, something better than nothing!!
