### ISSUE TITLE
Compile failed on Xcode 15.3

### ISSUE THREAD

**Issue by canaanyjn** [rryam/MusadoraKit#38]
Hi Rudrank,
After I upgraded to Xcode 15.3, the compilation keeps failing:
<img width="604" alt="image" src="https://github.com/rryam/MusadoraKit/assets/7188491/b73b0ec2-6c1d-44d2-bcab-f93d536ed9a0">
<img width="1410" alt="image" src="https://github.com/rryam/MusadoraKit/assets/7188491/26d8d3a0-6468-4b70-b7a4-8cf120e10af3">

**Comment by canaanyjn** [comment]
No, I am only using `MusadoraKit` in my project

**Comment by rudrankriyam** [comment]
I just released `4.2.0`, can you please try that and let me know?

**Comment by canaanyjn** [comment]
It works! Thank you very much~
