### ISSUE TITLE
Create RadioShow and Curator for iOS 15.0 to iOS 15.3

### ISSUE THREAD

**Issue by rudrankriyam** [rryam/MusadoraKit#4]
Currently, in Musickit, these items are iOS 15.4+ only. Create a version similar to MusicKit for iOS 15.0 to iOS 15.3

**Comment by rudrankriyam** [comment]
[RadioShow](https://developer.apple.com/documentation/musickit/radioshow): 7 properties to create using a custom decoder. 

[Curator](https://developer.apple.com/documentation/musickit/curator): 7 properties to create using a custom decoder.

Have a look at this thread here to under how both of them work - Accessing details about the Curator
https://developer.apple.com/forums/thread/702584?answerId=707930022#707930022

**Comment by paulcanyon** [comment]
This might help @rudrankriyam ~ https://www.appcoda.com/musickit-music-api/

**Comment by paulcanyon** [comment]
Why does it have _**iOS 15.0 - 15.3**_ instead of **`iOS 13` - `iOS 15.3`**?

**Comment by paulcanyon** [comment]
You can generate Apple Music JWT Token for support from iOS 13 and forward, I think..

**Comment by rudrankriyam** [comment]
Hi @paulcanyon, this framework is a companion to the **MusicKit** framework by Apple, written in Swift and for SwiftUI. It targets iOS 15+; however `RadioShow` and `Curator` were added later in iOS 15.4+. 

Hence, the issue is to create the structures for iOS 15 to 15.3

**Comment by rudrankriyam** [comment]
As iOS 16 adoption is increasing, and most of the users are iOS 15.4+, I'm closing this issue.
