### ISSUE TITLE
Adding Songs to playList takes time

### ISSUE THREAD

**Issue by Abdulganiylawal** [rryam/MusadoraKit#40]
<img width="1027" alt="Screenshot 2024-05-02 at 17 51 43" src="https://github.com/rryam/MusadoraKit/assets/110787491/6b3c52f7-9a80-4c93-831a-20563fb3e423">

The add function initially returns false, but after some time, the songs are successfully added to the playlist and I keep getting this error
Attempted to register account monitor for types client is not authorized to access: {(
    "com.apple.account.iTunesStore"
)}

**Comment by rudrankriyam** [comment]
The error: 

```
Attempted to register account monitor for types client is not authorized to access: {(
"com.apple.account.iTunesStore"
)}
```

Can be ignored as it is not relevant. 

For the first part, it does take some time to add songs to the playlist, similar to how it takes some time to create a new playlist. I will look into it on how the success should wait and return `true` when the songs are added

**Comment by Abdulganiylawal** [comment]
Okay.Thanks
