### ISSUE TITLE
MusicCatalogResourcesRequest and MusicLibraryResourcesRequest error Unauthorized

### ISSUE THREAD

**Issue by 666bsw** [rryam/MusadoraKit#44]
Hello!
 MCatalog.song(id: id), MusicCatalogResourcesRequest and MusicLibraryResourcesRequest
response Failed to parse body of response with status code Unauthorized (401)
what am i doing wrong?
music kit authorization request completed.
music subscription available.

Best regards

**Comment by rudrankriyam** [comment]
That should not happen if the authorisation request is completed and a subscription is available. Have you checked marked MusicKit for your identifier under Certificates and Identifiers?

**Comment by 666bsw** [comment]
Authorization request completed. Subscription to MusicKit is available. Maybe you need to get a user token?

**Comment by rudrankriyam** [comment]
You do not require the user token for catalog requests
