### ISSUE TITLE
Support for Custom Language Path in JSON File Retrieval

### ISSUE THREAD

**Issue by nbmisen** [rryam/MusadoraKit#45]
## Is your feature request related to a problem? Please describe.
I'm developing a multilingual music application, but the current `HundredBestAlbumRequest` only retrieves JSON files in English. This limitation prevents me from providing localized content for users who speak different languages.

## Describe the solution you'd like
I propose adding support for a customizable language path in the component configuration. Specifically, I'd like to be able to modify the path as follows:

```swift
components.path = "/content/us/\(language)/\(position).json"
```

This change would allow for easy retrieval of language-specific JSON files. For example, changing `en-us` to `zh-cn` in the path would successfully fetch the Chinese version of the content.

## Additional context
I've already tested this approach manually, and it successfully retrieves the Chinese version of the content. 

Thank you for considering this feature request. It would significantly improve the functionality and reach of applications built using this component.

**Comment by rudrankriyam** [comment]
I have released a new version: https://github.com/rryam/MusadoraKit/releases/tag/v5.0.1

You can use it like: 

```swift
let album = try await MRecommendation.hundredBestAlbum(at: 99, storefront: "zh-cn")

let albums = try await allHundredBestAlbums(storefront: "zh-cn")
```

Also, you can add your app to the README: https://github.com/rryam/MusadoraKit?tab=readme-ov-file#apps-using-musadorakit

谢谢!

**Comment by nbmisen** [comment]
Wow, I apologize for my delayed response. I'm impressed by how quickly new features have been added.

However, I regret to inform you that I overlooked a crucial aspect earlier - some languages require modifications to the country path as well. 

For instance (I'm not certain about the origin of this API, but I've tested and confirmed a few):
- Japanese: https://100best.music.apple.com/content/jp/ja-jp/1.json
- Korean: https://100best.music.apple.com/content/kr/ko-kr/1.json

It seems we need to implement country settings as well. LOL! Should I create a new issue for this?

I haven't released my app yet. When I do publish it in the future, I'll add it to the README.
Thank you very much!

**Comment by rudrankriyam** [comment]
Apologies for not testing it. I am thinking of a better way to work with the storefront and the language details. I will think about it and fix it. For now, I won't be able to work on this till 16th of September because I need to release my apps for iOS 18!

You do not have to create a new issue for this, this will suffice. Thank you very much!

**Comment by rudrankriyam** [comment]
Hello, 
I have added a simple change; please test it and let me know if it works fine now. Thank you!

```swift
let album = try await MRecommendation.hundredBestAlbum(at: 99, storefront: "jp", region: "ja-jp")

let albums = try await allHundredBestAlbums(storefront: "jr", region: "ko-kr")
```

**Comment by nbmisen** [comment]
I've tested it and it works very well. Thank you very much again~
