### ISSUE TITLE
Searching Catalog by Genre 

### ISSUE THREAD

**Issue by mjdierkes** [rryam/MusadoraKit#5]
Hi Rudrank,

Great Package!
Is it possible to search for songs by their Genre ID? 
I haven't been able to find anything regarding Genre search yet.

**Comment by rudrankriyam** [comment]
Hi there! 

Thank you for appreciating MusadoraKit! 

I am not sure there is any functionality like that in the Apple Music API. 

However, you can get a chart for a particular genre that contains the most played songs: 

```swift 
var request = MusicCatalogChartRequest(types: [Song.self])
request.genre = "34"
let response = try await request.response()

print(response.songs)
``` 

Let me know what you think!

**Comment by mjdierkes** [comment]
Never mind, your blog helped out :)
[https://rudrank.blog/exploring-musickit-genres](url)

**Comment by rudrankriyam** [comment]
Just want to bump up this issue again, MusadoraKit does not have the capability to fetch all the genres, right? @mjdierkes

**Comment by rudrankriyam** [comment]
Don't want to annoy you, but now you can get the catalog top chart genres simply by: 

```swift 
print(try await MusadoraKit.catalogTopChartsGenres())
```

Let me know what you think!
