### ISSUE TITLE
How does MusicKit love/unlove a song?

### ISSUE THREAD

**Issue by Kejiasir** [rryam/MusadoraKit#6]
Hi, how does MusicKit love/unlove a song? Do you know of any related APIs?

![20220630191558](https://user-images.githubusercontent.com/14361443/176664898-69c57d39-73d8-4898-8f1e-67a3606bf5a3.jpg)

**Comment by rudrankriyam** [comment]
Heya! MusicKit does not have a rating API as of yet. 

However, you can use MusadoraKit for this purpose. For example, to add a **Love** rating for a particular song, you can do so by:

```swift
let id: MusicItemID = "1628890886"
let request = MusicCatalogRatingAddRequest<Song>(matching: \.id, equalTo: id, rating: .loved)
let response = try await request.response()

print(response.items)
```

If it is a success, you will get the rating that contains the identifier of the music item, and the rating. 

Let me know if you use it!

**Comment by Kejiasir** [comment]
wow, awesome, this helped me, thank you.
